version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - revive
    - unparam
    - unconvert
  settings:
    revive:
      rules:
        - name: var-naming
        - name: unexported-return
        - name: exported
    gocritic:
      disabled-checks:
        - ifElseChain

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
